baseURL = "https://serverless.org.nz"
languageCode = "en-us"
title = "ServerlessDays Auckland"

[params]
    logo = "/images/ServerlessDaysAuckland2020.png"
    tldr= "/images/tealdeer.jpg"
    description = "A community based conference focusing on Serverless based platforms and technologies. Auckland, April 20, 2020"
    mascot = "https://res.cloudinary.com/dtsyxzxfx/image/upload/f_auto,q_auto/v1577987547/2020/anteater_mascot.png"
    date = "Postponed"
    city = "Auckland"
    twitter = "ServerlessAKL"
    instagram = "serverless_sthlm"
    email = "auckland@serverlessdays.io"
    backgroundImage = "https://res.cloudinary.com/dtsyxzxfx/image/upload/w_1800,c_scale,f_auto,q_auto:low/v1577923266/2020/dan-freeman-hIKVSVKH7No-unsplash.jpg"
    prospectus = "/ServerlessDays_Auckland2020_Prospectus_v1.3.pdf"
    ticketDate = "1 January 2020"
    ticketSaleUrl = "https://ti.to/serverlessdays-auckland/2020"
    cfpDate = "3 Dec 2019"
    cfpEndDate = "2 March 2020"
    cfpUrl = "https://www.papercall.io/serverlessdaysauckland2020"

[[params.dates]]
    date = "03 December 2019"   
    text = "CFP Opens"
    done = true

[[params.dates]]
    date = "01 January 2020"
    text = "Tickets go on sale"
    done = true

[[params.dates]]
    date = "02 March 2020"
    text = "CFP closes"
    done = true



[[params.tickets]]
    ticket = "Early Bird"   
    text = "Limited Availability until 15th Jan 2020"
    price = "NZ$39"
    done = false

[[params.tickets]]
    ticket = "General Admission + Workshops"
    text = "Entry to the conference, and workshops on following day"
    price = "NZ$49"
    done = false

[[params.tickets]]
    ticket = "General Admission + Donate a ticket"
    text = "Feeling the community spirit? Add a donation to your ticket to sponsor somebody else who otherwise might not be able to participate in the event."
    price = "Minimum NZ$49 + your generosity"
    done = false

[[params.tickets]]
    ticket = "T-Shirt"
    text = "Grab a great Tee to remember the day. Purchase with ticket, and collect on registration"
    price = "NZ$20"
    done = false



[params.venue]
    name = "The University of Auckland, Sir Owen G Glenn Building"
    link = "https://www.auckland.ac.nz/en/business/about-business-school/our-faculty/oggb.html"
    map = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12770.186828378988!2d174.7709701124116!3d-36.85333079431854!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x1e535b2e4292ac86!2sSir%20Owen%20G%20Glenn%20Building!5e0!3m2!1sen!2snz!4v1575188734287!5m2!1sen!2snz"
    text = "Located in New Zealand's largest city, the Business School's purpose-built Sir Owen G Glenn Building dominates the Grafton Road side of the city campus at the heart of Auckland's main commercial centre."

[[params.agenda]]
    time = "8:00 - 9:00"
    type = "coffee"
    title = "Registration"
[[params.agenda]]
    time = "9:00 - 9:10"
    type = "talk"
    title = "Opening Remarks"
[[params.agenda]]
    time = "9:10 - 9:45"
    type = "talk"
    talk = "James.Beswick"
[[params.agenda]]
    time = "9:45 - 10:15"
    type = "talk"
    talk = "Farrah.Campbell"
[[params.agenda]]
    time = "10:15 - 11:00"
    type = "coffee"
    title = "Morning break"
[[params.agenda]]
    time = "11:00 - 11:35"
    type = "talk"
    talk = "ToBeAnnounced"
[[params.agenda]]
    time = "11:35 - 12:15"
    type = "talk"
    talk = "ToBeAnnounced"
[[params.agenda]]
    time = "12:15 - 13:45"
    type = "lunch"
    title = "Lunch"
[[params.agenda]]
    time = "13:50 - 14:20"
    type = "talk"
    title = "Panel discussion"
[[params.agenda]]
    time = "14:20 - 14:50"
    type = "talk"
    talk = "ToBeAnnounced"
[[params.agenda]]
    time = "14:50 - 15:20"
    type = "talk"
    talk = "ToBeAnnounced"
[[params.agenda]]
    time = "15:20 - 15:35"
    type = "talk"
    talk = "Damon.Williams"
[[params.agenda]]
    time = "15:35 - 15:45"
    type = "talk"
    talk = "ToBeAnnounced"
[[params.agenda]]
    time = "15:45 - 16:30"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "16:30 - 17:00"
    type = "talk"
    talk = "ToBeAnnounced"
[[params.agenda]]
    time = "17:00 - 17:30"
    type = "talk"
    talk = "Randall.Hunt"
[[params.agenda]]
    time = "17:30 - 18:30"
    type = "lunch"
    title = "Closing Remarks and drinks reception"
