baseURL = "https://serverless.org.nz"
languageCode = "en-us"
title = "ServerlessDays Auckland"

[params]
    logo = "/images/Logo1.png"
    tldr= "/images/tealdeer.jpg"
    description = "A community based conference focusing on Serverless based platforms and technologies. Auckland, April 20, 2020"
    mascot = "/images/Anteater_mascot.png"
    date = "20 April 2020"
    city = "Auckland"
    twitter = "ServerlessAKL"
    instagram = "serverless_sthlm"
    email = "auckland@serverlessdays.io"
    backgroundImage = "/images/dan-freeman-hIKVSVKH7No-unsplash.jpg"
    prospectus = "/ServerlessDays_Auckland2020_Prospectus_v1.3.pdf"
    ticketDate = "1 January 2020"
    ticketSaleUrl = "https://somewhere.eventbrite.com"
    cfpDate = "3 Dec 2019"
    cfpEndDate = "2 March 2020"
    cfpUrl = "https://www.papercall.io/serverlessdaysauckland2020"

[[params.dates]]
    date = "03 December 2019"
    text = "CFP Opens"
    done = false

[[params.dates]]
    date = "1 January 2020"
    text = "Tickets go on sale"
    done = false

[[params.dates]]
    date = "2 March 2020"
    text = "CFP closes"
    done = false

[[params.dates]]
    date = "15 March 2020"
    text = "Final speaker announcement"
    done = false    

[[params.dates]]
    date = "20 April 2020"
    text = "ServerlessDays Auckland @ Auckland University"
    done = false

[[params.dates]]
    date = "25 october 2019"
    text = "Workshops"
    done = false

[params.venue]
    name = "The University of Auckland, Sir Owen G Glenn Building"
    link = "https://www.auckland.ac.nz/en/business/about-business-school/our-faculty/oggb.html"
    map = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12770.186828378988!2d174.7709701124116!3d-36.85333079431854!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x1e535b2e4292ac86!2sSir%20Owen%20G%20Glenn%20Building!5e0!3m2!1sen!2snz!4v1575188734287!5m2!1sen!2snz"
    text = "Located in New Zealand's largest city, the Business School's purpose-built Sir Owen G Glenn Building dominates the Grafton Road side of the city campus at the heart of Auckland's main commercial centre."

[[params.agenda]]
    time = "8:00 - 9:00"
    type = "coffee"
    title = "Registration & Breakfast"
[[params.agenda]]
    time = "9:00 - 9:15"
    type = "coffee"
    title = "Opening Remarks"
[[params.agenda]]
    time = "9:15 - 9:45"
    type = "talk"
    talk = "Richard.Boyd"
[[params.agenda]]
    time = "9:50 - 10:20"
    type = "talk"
    talk = "Simon.Aronsson"
[[params.agenda]]
    time = "10:20 - 10:50"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "10:50 - 11:20"
    type = "talk"
    talk = "Angela.Timofte"
[[params.agenda]]
    time = "11:25 - 11:55"
    type = "talk"
    talk = "Ory.Segal"
[[params.agenda]]
    time = "12:00 - 13:10"
    type = "lunch"
    talk = ""
[[params.agenda]]
    time = "13:10 - 13:40"
    type = "talk"
    talk = "Bruno.Amaro.Almeida"
[[params.agenda]]
    time = "13:45 - 14:15"
    type = "talk"
    talk = "Bret.McGowen"
[[params.agenda]]
    time = "14:20 - 14:55"
    type = "talk"
    talk = "Heitor.Lessa"
[[params.agenda]]
    time = "14:55 - 15:20"
    type = "coffee"
    title = "Coffee Break"
[[params.agenda]]
    time = "15:20 - 15:50"
    type = "talk"
    talk = "Katarina.Svedman"
[[params.agenda]]
    time = "15:55 - 16:25"
    type = "talk"
    talk = "Efi.Merdler.Kravitz"
[[params.agenda]]
    time = "16:30 - 17:00"
    type = "talk"
    talk = "James.Beswick"
[[params.agenda]]
    time = "17:00 - 17:15"
    type = "coffee"
    title = "Closing Remarks"
[[params.agenda]]
    time = "17:30 - 19:30"
    type = "coffee"
    title = "Networking, Dringks and nibbles"
